---
abstract: 'Git Changesets, tools for managing you git changes'
author:
  - 'Grant Street Group'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131490'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Gitc
requires:
  Algorithm::Dependency::Ordered: 0
  Algorithm::Dependency::Source::HoA: 0
  App::Gitc::Config: 0
  App::Gitc::ListFormat::Base: 0
  Carp: 0
  Class::MOP: 0
  Cwd: 0
  Date::Format: 0
  Date::Parse: 0
  Date::PeriodParser: 0
  Email::Simple: 0
  Exporter: 0
  File::Spec: 0
  File::Temp: 0
  GSG::Eventum: 0
  Getopt::Long: 0
  Hash::Merge::Simple: 0
  JIRA::Client: 0
  JIRA::Client::REST: 0
  List::MoreUtils: 0
  List::Util: 0
  POSIX: 0
  Pithub::Issues: 0
  Term::ReadLine: 0
  Test::More: 0
  Text::Levenshtein: 0
  Time::Local: 0
  Try::Tiny: 0
  YAML: 0
  YAML::Syck: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/GrantStreetGroup/gitc/issues
  repository: git://github.com/GrantStreetGroup/gitc.git
version: 0.58
